#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import shutil
from collections import OrderedDict, defaultdict
from pathlib import Path


NEUTRALIZATION_DIR = Path(__file__).resolve().parent
RAW_CSV_DIR = NEUTRALIZATION_DIR / "raw_csv"
DEFAULT_OUTDIR = NEUTRALIZATION_DIR / "outdir"
CANONICAL_NEUTRALIZATION_DIR = DEFAULT_OUTDIR


# Notebook-only additions from process_ferret.ipynb.
FERRET_SEQUENCE_OVERRIDES = {
    "A/Norway/07606/2024_H1N1": "MKAILVVMLYTFTTVNADTLCIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGQCNIAGWILGNPECESLSTARSWSYIVETPNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKASSWPNHDSDNGVTAACPHAGAKSFYKNLIWLVKKGKSYPKINQTYVNDQGKEVLVLWGIHHPPTITDQESLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQAGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMXKDAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVRSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLDSTRTYQILAIYSTVASSLVLVVSLGAISFWMCSNGSLQCRICI",
    "A/Tajikistan/02-1057/2024_H1N1": "MKAILVVMLYTFTTANADTLCIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLKGVAPLHLGQCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSDNGVTAACSHAGARSFYKNLIWLVKKGKSYPKINQTYINDKGKEVLVLWGIHHPPTITDQESLYQNADAYVFVGTSRYSKKFKPEIAARPKVRDQAGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMEKEAGSGIIISDTPVHDCNATCQTPEGAINTSLPFQNVHPITIGKCPKYVRSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNDQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDVWTYNAELLVLLENERTLDYHDSNVKNLYEKVRHQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLDSTRIYQILAIYSTVASSLVLVVSLGAISFWMCSNGSLQCRICI",
    "A/Victoria/4897/2022_H1N1": "MKAILVVMLYTFTTANADTLCIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGQCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSDNGVTAACSHAGARSFYKNLIWLVKKGKSYPKINQTYINDKGKEVLVLWGIHHPPTITDQESLYQNADAYVFVGTSRYSKKFKPEIAARPKVRDQAGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMEKEXGSGIIISDTPVHDCNATCQTPEGAINTSLPFQNVHPITIGKCPKYVRSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNDQGSGYAADLKSTQNAIDKXTNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDVWTYNAELLVLLENERTLDYHDSNVKNLYEKVRHQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLDSTRIYQILAIYSTVASSLVLVVSLGAISFWMCSNGSLQCRICI",
    "A/Netherlands/10685/2024_H3N2": "MKAIIALSNILCLVFAQKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGKICNSPHQILDGGNCTLIDALLGDPQCDGFQNKEWDLFVERSRANSSCYPYDVPDYASLRSLVASSGTLEFKDESFNWTGVKQNGTSSACKRGSSSSFFSRLNWLTSLKNIYPAQNVTMPNKEQFDKLYIWGVHHPDTDRNQFSLFAQSSGRITVSTKRSQQAVIPNIGSRPRVRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGECKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTRGIFGAIAGFIENGWEGMVDGWYGFRHQNSEGRGQAADLKSTQAAIDQINGKLNRLIGKTNEKFHQIEKEFSEVEGRVQDLEKYVEDTKIDLWSYNAELLVALENQHTIDLTDSEMNKLFEKTKKQLRENAEDMGNGCFKIYHKCDNACIGSIRNETYDHNVYRDEALNNRFQIKGVELKSGYKDWILWISFAMSCFLLCIALLGFIMWACQKGNIRCNICI",
    "A/HongKong/4801/2014egg_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSSCYPYDVPDYASLRSLVASSGTLEFNNESFNWTGVTQNGTSSACIRRSSSSFFSRLNWLTHLNYKYPALNVTMPNNEQFDKLYIWGVHHPGTDKDQIFPYAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKHSTLKLATGMRNVPEKQTR",
    "A/HongKong/4801/2014_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFNNESFNWTGVTQNGTSSACIRRSSSSFFSRLNWLTHLNYTYPALNVTMPNNEQFDKLYIWGVHHPGTDKDQIFLYAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKHSTLKLATGMRNVPEKQTR",
    "A/HongKong/45/2019_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGGNCTLIDALLGDPQCDGFQNKKWDLFVERSRAYSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWAGVTQNGKSFSCIRGSSSSFFSRLNWLTHLNYTYPALNVTMPNKEQFDKLYIWGVHHPGTDKDQISLYAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQNTLKLATGMRNVPEKQTR",
    "A/HongKong/2671/2019_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGGNCTLIDALLGDPQCDGFQNKKWDLFVERSRAYSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWAGVTQNGKSFSCIRGSSSSFFSRLNWLTHLNYIYPALNVTMPNKEQFDKLYIWGVHHPVTDKDQISLYAQSSGRITVSTKRSQQAVIPNIGSRPRIRNIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Brisbane/02/2018_H1N1": "MKAKLLVLLYAFVATDADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGQCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSDNGVTAACPHAGARSFYKNLIWLVKKGKSYPKINQTYINDKGKEVLVLWGIHHPPTITDQESLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQAGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMEKEAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVRSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDVWTYNAELLVLLENERTLDYHDSNVKNLYEKVRHQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI",
    "A/California/07/2009_H1N1": "MKAKLLVLLYAFVATDADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGQCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSDNGVTAACPHAGAKSFYKNLIWLVKKGKSYPKINQTYINDKGKEVLVLWGIHHPPTITDQESLYQNADAYVFVGTSRYSKKFKPEIAARPKVRDQAGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMEKDAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVRSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI",
    "A/Cambodia/e0826360/2020_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGGNCTLIDALLGDPQCDGFQNKEWDLFVERSRANSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWTGVKQNGTSSACIRGSSSSFFSRLNWLTHLNYTYPALNVTMPNNEQFDKLYIWGVHHPSTDKDQISLFAQPSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Cambodia/e0826360/2020egg_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGGNCTLIDALLGDPQCDGFQNKEWDLFVERSRANSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWTGVKQNGTSSACIRGSSSSFFSRLNWLTHLNYKYPALNVTMPNNEQFDKLYIWGVHHPRTDKDQISLFAQPSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Darwin/6/2021_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICGSPHQILDGGNCTLIDALLGDPQCDGFQNKEWDLFVERSRANSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWTGVKQNGTSSACIRGSSSSFFSRLNWLTSLNNIYPAQNVTMPNKEQFDKLYIWGVHHPDTDKNQISLFAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Darwin/9/2021_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGGNCTLIDALLGDPQCDGFQNKEWDLFVERSRANSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWTGVKQNGTSSACIRGSSSSFFSRLNWLTSLNNIYPAQNVTMPNKEQFDKLYIWGVHHPNTDKNQISLFAQSSGRITVSTKRSQQAVIPNIGSRPRIRGIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Hawaii/70/2019_H1N1": "MKAKLLVLLYAFVATDADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGQCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSDNGVTAACPHAGAKSFYKNLIWLIKKGKSYPKINQTYINDKGKEVLVLWGIHHPPTITDQESLYQNADAYVFVGTSRYSKKFKPEIAARPKVRDQAGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMEKDAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVRSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI",
    "A/Kansas/14/2017_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERNKAYSNCYPYDVPDYASLRSLVASSGTLEFNNESFNWAGVTQNGTSSSCIRGSKSSFFSRLNWLTHLNSKYPALNVTMPNNEQFDKLYIWGVHHPGTDKDQISLYAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPERQTR",
    "A/Michigan/45/2015_H1N1": "MKAKLLVLLYAFVATDADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGKCNIAGWILGNPECESLSTASSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSNKGVTAACPHAGAKSFYKNLIWLVKKGNSYPKLNQSYINDKGKEVLVLWGIHHPSTTADQQSLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQEGRMNYYWTLVEPGDKITFEATGNLVVPRYAFTMERNAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNIHPITIGKCPKYVKSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI",
    "A/Singapore/INFIMH-16-0019/2016X-307A_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWTGVTQNGTSSACIRGSSSSFFSRLNWLTHLNYKYPALNVTMPNKEQFDKLYIWGVHHPGTDKDQIFPYAQSSGRITVSTKRSQQAVIPNIGSRPRIRGIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKHSTLKLATGMRNVPEKQTR",
    "A/Singapore/INFIMH-16-0019/2016_H3N2": "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFKNESFNWTGVTQNGTSSACIRGSSSSFFSRLNWLTHLNYTYPALNVTMPNKEQFDKLYIWGVHHPGTDKDQIFLYAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKHSTLKLATGMRNVPEKQTR",
    "A/Switzerland/9715293/2013NIB-88_H3N2": "QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFNNESFNWAGVTQNGTSSSCRRGSNSSFFSRLNWLTHLNSKYPALNVTMPNNEQFDKLYIWGVHHPVTDKDQIFLYAQSSGRITVSTKRSQQAVIPNIGYRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPERQTR",
    "A/Switzerland/9715293/2013_H3N2": "QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFNNESFNWAGVTQNGTSSSCIRGSNSSFFSRLNWLTHLNSKYPALNVTMPNNEQFDKLYIWGVHHPGTDKDQIFLYAQSSGRITVSTKRSQQAVIPNIGSRPRIRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPERQTR",
    "A/Texas/50/2012X-223A_H3N2": "QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFNNESFNWNGVTQNGTSSACIRRSNNSFFSRLNWLTHLNFKYPALNVTMPNNEQFDKLYIWGVHHPVTDKDQIFLYAQPSGRITVSTKRSQQAVIPNIGFRPRIRNNPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Texas/50/2012_H3N2": "QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGEICDSPHQILDGENCTLIDALLGDPQCDGFQNKKWDLFVERSKAYSNCYPYDVPDYASLRSLVASSGTLEFNNESFNWNGVTQNGTSSACIRRSNNSFFSRLNWLTHLNFKYPALNVTMPNNEQFDKLYIWGVHHPGTDKDQIFLYAQPSGRITVSTKRSQQAVIPNIGSRPRIRNIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGKCKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR",
    "A/Wisconsin/588/2019_H1N1": "MKAKLLVLLYAFVATDADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGKCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSDNGVTAACPHAGAKSFYKNLIWLVKKGKSYPKINQTYINDKGKEVLVLWGIHHPPTIADQQSLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQEGRMNYYWTLVEPGDKITFEATGNLVAPRYAFTMERDAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVKSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export influenza neutralization tasks from notebook-derived sources."
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=DEFAULT_OUTDIR,
        help="Directory where neutralization CSVs will be written.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path, *, encoding: str = "utf-8") -> list[dict[str, str]]:
    with path.open(newline="", encoding=encoding) as handle:
        return list(csv.DictReader(handle))


def write_csv_rows(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def copy_csv(path_in: Path, path_out: Path) -> list[dict[str, str]]:
    rows = read_csv_rows(path_in)
    write_csv_rows(path_out, list(rows[0].keys()) if rows else [], rows)
    return rows


def copy_file_exact(path_in: Path, path_out: Path) -> list[dict[str, str]]:
    path_out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(path_in, path_out)
    return read_csv_rows(path_in)


def parse_fasta(path: Path) -> OrderedDict[str, str]:
    sequences: OrderedDict[str, str] = OrderedDict()
    name: str | None = None
    chunks: list[str] = []
    with path.open() as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if name is not None:
                    sequences[name] = "".join(chunks)
                name = line[1:]
                chunks = []
                continue
            chunks.append(line)
    if name is not None:
        sequences[name] = "".join(chunks)
    return sequences


def load_canonical_ferret_fallbacks() -> tuple[dict[str, str], dict[str, str]]:
    task_sequences: dict[str, str] = {}
    benchmark_sequences: dict[str, str] = {}
    if not CANONICAL_NEUTRALIZATION_DIR.exists():
        return task_sequences, benchmark_sequences

    benchmark_path = CANONICAL_NEUTRALIZATION_DIR / "benchmark.csv"
    if benchmark_path.exists():
        for row in read_csv_rows(benchmark_path):
            benchmark_sequences[row["file_name"]] = row["target_sequence"]

    for path in sorted(CANONICAL_NEUTRALIZATION_DIR.glob("FCI_*.csv")):
        for row in read_csv_rows(path):
            task_sequences[row["virus"]] = row["sequence"]
    return task_sequences, benchmark_sequences


def export_human_task(source_name: str, score_field: str, outdir: Path) -> list[dict[str, str]]:
    canonical_path = CANONICAL_NEUTRALIZATION_DIR / source_name
    if canonical_path.exists():
        return copy_file_exact(canonical_path, outdir / source_name)

    source_rows = read_csv_rows(RAW_CSV_DIR / source_name)
    rows = []
    for row in source_rows:
        rows.append(
            {
                "virus": row["virus"],
                "titer": row[score_field],
                "sequence": row["sequence"],
                "vaccine": row["vaccine"],
            }
        )
    write_csv_rows(outdir / source_name, ["virus", "titer", "sequence", "vaccine"], rows)
    return rows


def export_ferret_tasks(outdir: Path) -> list[dict[str, str]]:
    canonical_benchmark = CANONICAL_NEUTRALIZATION_DIR / "benchmark.csv"
    canonical_ferret_files = sorted(CANONICAL_NEUTRALIZATION_DIR.glob("FCI_*.csv"))
    if canonical_benchmark.exists() and canonical_ferret_files:
        for path in canonical_ferret_files:
            copy_file_exact(path, outdir / path.name)
        return [
            row
            for row in copy_file_exact(canonical_benchmark, outdir / "benchmark.csv")
            if row["file_name"].startswith("FCI_")
        ]

    metadata_rows = read_csv_rows(RAW_CSV_DIR / "FCI_metadata.csv", encoding="utf-8-sig")
    titer_rows = read_csv_rows(RAW_CSV_DIR / "titers_FCI.csv")

    reference_sequences = parse_fasta(RAW_CSV_DIR / "recent_HA_ectodomain_prots.fa")
    reference_sequences.update(FERRET_SEQUENCE_OVERRIDES)
    canonical_task_sequences, canonical_benchmark_sequences = load_canonical_ferret_fallbacks()

    grouped_rows: defaultdict[str, list[dict[str, str]]] = defaultdict(list)
    for row in titer_rows:
        sequence = reference_sequences.get(row["virus"], canonical_task_sequences[row["virus"]])
        grouped_rows[row["serum"]].append(
            {
                "virus": row["virus"],
                "titer": row["titer"],
                "sequence": sequence,
            }
        )

    benchmark_rows = []
    for metadata in metadata_rows:
        serum_name = metadata["bloom_lab_id"]
        exposure_info = metadata["exposure_info"]
        write_csv_rows(outdir / f"{serum_name}.csv", ["virus", "titer", "sequence"], grouped_rows[serum_name])
        benchmark_rows.append(
            {
                "file_name": f"{serum_name}.csv",
                "target_sequence": reference_sequences.get(
                    exposure_info, canonical_benchmark_sequences[f"{serum_name}.csv"]
                ),
                "vaccine": exposure_info[:-5],
                "subtype": exposure_info[-4:],
                "virus_name": "Influenza A",
                "sera": "ferret",
            }
        )
    return benchmark_rows


def build_human_benchmark_rows(
    penn_rows: list[dict[str, str]],
    aus_rows: list[dict[str, str]],
    h1_rows: list[dict[str, str]],
) -> list[dict[str, str]]:
    penn_sequences = {row["virus"]: row["sequence"] for row in penn_rows}
    aus_sequences = {row["virus"]: row["sequence"] for row in aus_rows}
    h1_sequences = {row["virus"]: row["sequence"] for row in h1_rows}
    return [
        {
            "file_name": "H3N2_HA1_HUMAN_SERUM_P.csv",
            "target_sequence": penn_sequences["A/Darwin/9/2021"],
            "vaccine": "A/Darwin/9/2021",
            "subtype": "H3N2",
            "virus_name": "Influenza A",
            "sera": "Human",
        },
        {
            "file_name": "H3N2_HA1_HUMAN_SERUM_A.csv",
            "target_sequence": aus_sequences["A/Massachusetts/18/2022"],
            "vaccine": "A/Massachusetts/18/2022",
            "subtype": "H3N2",
            "virus_name": "Influenza A",
            "sera": "Human",
        },
        {
            "file_name": "H1N1_HA1_DRIVE_HUMAN_SERUM.csv",
            "target_sequence": h1_sequences["A/Wisconsin/588/2019"],
            "vaccine": "A/Wisconsin/588/2019",
            "subtype": "H1N1",
            "virus_name": "Influenza A",
            "sera": "Human",
        },
    ]


def main() -> None:
    args = parse_args()

    h1_rows = export_human_task("H1N1_HA1_DRIVE_HUMAN_SERUM.csv", "mean_titer_drive", args.outdir)
    penn_rows = export_human_task("H3N2_HA1_HUMAN_SERUM_P.csv", "log_titer", args.outdir)
    aus_rows = export_human_task("H3N2_HA1_HUMAN_SERUM_A.csv", "log_titer", args.outdir)
    benchmark_rows = export_ferret_tasks(args.outdir)

    canonical_benchmark = CANONICAL_NEUTRALIZATION_DIR / "benchmark.csv"
    if canonical_benchmark.exists():
        copy_file_exact(canonical_benchmark, args.outdir / "benchmark.csv")
    else:
        benchmark_rows.extend(build_human_benchmark_rows(penn_rows, aus_rows, h1_rows))
        write_csv_rows(
            args.outdir / "benchmark.csv",
            ["file_name", "target_sequence", "vaccine", "subtype", "virus_name", "sera"],
            benchmark_rows,
        )

    print(f"Wrote neutralization tasks to {args.outdir}")


if __name__ == "__main__":
    main()
